config/routes.rb
Rails.application.routes.draw do

  root 'home#home'
  
  post '/contact' => 'home#create'
   
  
  resources :home do
    end
      

end

app/models/contact.rb
class Contact

    include ActiveModel::Model
    include ActiveModel::Validations
    
    attr_accessor :name, :email, :message
    
validates :name, presence: true, length: {maximum: 50}
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, length: {maximum: 255},
                            format: {with: VALID_EMAIL_REGEX}
validates :message, presence: true

end
    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
def home
    @contact = Contact.new
end

def new
end

def create
    @contact = Contact.new(contact_form_params) 
    
    if @contact.valid?
      ContactMailer.new_contact(@contact).deliver_now
      flash[:success] = "Your message has been sent."
      redirect_to root_path
    else
      flash.now[:danger] = "Your message could not be sent based on the following:"
      render 'home'
    end
end


private
def contact_form_params
    params.require(:contact).permit(:name, :email, :message)
end    


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_errormessages.html.erb
       <% unless flash.empty? %>
                            <div id="error_explanation">
                                <div class="alert alert-success">
                                    <% flash.each do |error,message| %>
                                    <ul>
                                        <li> <%= message %></li>
                                    </ul>   
                                </div>
                            </div>       
                                     <% end %>
                        <% end %> 
       
       <!--                  <%= render 'home/errormessages' %>
    <% if @contact.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-success">
        <% @contact.errors.each do |message| %>
        <ul>
            <li> <%= message %></li>
        </ul>   
        </div>
    </div>       
        <% end %>
     <% end %>   -->
     
                         <% if not flash.empty? %>
                            <div id="error_explanation">
                                <div class="alert alert-success">
                                    <%= @contact.flash.each do |message| %>
                                    <ul>
                                        <li> <%= message %></li>
                                    </ul>   
                                </div>
                            </div>       
                                     <% end %>
                        <% end %> 

app/views/home/home.html.erb

    <!-- Header -->
    <header>
        <div class="container" id="maincontent" tabindex="-1">
            <div class="row">
                <div class="col-lg-12">
                    <%=image_tag("profile.png", :class => "img-responsive") %>
                    <div class="intro-text">
                        <h1 class="name">Start Bootstrap</h1>
                        <hr class="star-light">
                        <span class="skills">Web Developer - Graphic Artist - User Experience Designer</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- theme Grid Section -->
    <section id="theme">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Sample Themes</h2>
                    <hr class="star-primary">
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4 theme-item">
                    <a href="#themeModal1" class="theme-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <%=image_tag("theme/cabin.png", :class => "img-responsive") %>
                    </a>
                </div>
                <div class="col-sm-4 theme-item">
                    <a href="#themeModal2" class="theme-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <%=image_tag("theme/cake.png", :class => "img-responsive", :alt => "Slice of Cake") %>
                    </a>
                </div>
                <div class="col-sm-4 theme-item">
                    <a href="#themeModal3" class="theme-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <%=image_tag("theme/circus.png", :class => "img-responsive", :alt => "Circus Tent") %>
                    </a>
                </div>
                <div class="col-sm-4 theme-item">
                    <a href="#themeModal4" class="theme-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <%=image_tag("theme/game.png", :class => "img-responsive", :alt => "Game Controller") %>
                    </a>
                </div>
                <div class="col-sm-4 theme-item">
                    <a href="#themeModal5" class="theme-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <%=image_tag("theme/safe.png", :class => "img-responsive", :alt => "Safe") %>
                    </a>
                </div>
                <div class="col-sm-4 theme-item">
                    <a href="#themeModal6" class="theme-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <%=image_tag("theme/submarine.png", :class => "img-responsive", :alt => "Submarine") %>
                    </a>
                </div>
            </div>
        </div>
    </section>
    
    <!-- About Section -->
    <section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>About</h2>
                    <hr class="star-light">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-lg-offset-2">
                    <p>Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization.</p>
                </div>
                <div class="col-lg-4">
                    <p>Whether you're a student looking to showcase your work, a professional looking to attract clients, or a graphic artist looking to share your projects, this template is the perfect starting point!</p>
                </div>
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <a href="#" class="btn btn-lg btn-outline">
                        <i class="fa fa-download"></i> Download Theme
                    </a>
                </div>
            </div>
        </div>
    </section>
    
    <section id="contact">
    <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Contact Me</h2>
                    <hr class="star-primary">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                <div id="error_explanation">
                    
                    <% if flash.any? %>
                    <% flash.each do |type, message| %>
                    <div class="alert flash-alert alert-<%= type %> alert-dismissable">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                
                                        <%= message %>
                                       
                       </div>             
                                 
                                 
                                 
                    <% end %>
                    <% end %>
                    <%= form_for @contact, url: contact_path(:anchor => "contact") do |f| %>
                    <!-- because flash shouldn't be empty nothing should show up-->
                    
                
                    <% if @contact.errors.any? %>
                        
                            <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                <% @contact.errors.full_messages.each do |msg| %>
                                    <ul>
                                        <li> <%= msg %></li>
                                       
                                    </ul>   
                                <%end%>   
                            </div>
                        </div> 
                        
                    <% end %> 
                        
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <%= f.label :name, 'Name' %>
                                <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <%= f.label :email, 'E-mail' %>
                                <%= f.text_field :email, class: 'form-control', placeholder: 'E-mail' %>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                              <%= f.label :message, 'Message' %>
                              <%= f.text_area :message, class: 'form-control', rows:"4", placeholder: 'Message' %>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <br>
                        <div id="success"></div>
                        <div class="row">
                            <div class="form-group col-xs-12">
                              <%= f.submit "Send", class: "btn btn-success btn-lg" %>
                              <% end %>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer -->
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3>Location</h3>
                        <p>3481 Melrose Place
                            <br>Beverly Hills, CA 90210</p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Made With</h3>
                        <div class="devicons">
                            
                                <i class="devicon-ruby-plain"></i><span class="sr-only">Ruby</span>
                            
                                <i class="devicon-rails-plain"></i><span class="sr-only">Rails</span>
                            
                                <i class="devicon-bootstrap-plain"></i><span class="sr-only">Bootstrap</span>
                            
                                <i class="devicon-css3-plain"></i><span class="sr-only">CSS3</span>
                            
                                <i class="devicon-javascript-plain"></i><span class="sr-only">Javascript</span>
                            
                        </div>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>About Freelancer</h3>
                        <p>Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; Your Website 2016
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-top page-scroll hidden-sm-up">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-arrow-up"></i>
        </a>
    </div>




app/views/layouts/_nav.html.erb
<div id="skipnav"><a href="#maincontent">Skip to main content</a></div>

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-toggleable-sm fixed-top justify-content-center" id="mainNav">
    <div class="page-scroll">
    <button class="navbar-toggler collapsed navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
    </button>
    <a href="#page-top" class="navbar-brand navbar-header w-50 mr-auto">Brand</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav ml-auto w-100 justify-content-end">
           <li class="hidden">
               <a href="#page-top"></a>
           </li>
            <li class="page-scroll">
                <a class="nav-link" href="#theme">Themes</a>
            </li>
            <li class="page-scroll">
                <a class="nav-link" href="#about">About</a>
            </li>
            <li class="page-scroll">
                <a class="nav-link" href="#contact">Contact</a>
            </li>
        </ul>
    </div>
    

    <!--<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display 
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling 
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#portfolio">Portfolio</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about">About</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>-->
            
            <!-- /.navbar-collapse -->

    
        <!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Freelancer - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', async: true %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.min.js' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>



    <!-- Custom Fonts -->
    <link href="https://github.com/BlackrockDigital/startbootstrap-freelancer/blob/master/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

<%= render "layouts/nav" %>
<%= yield %>





<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
  crossorigin="anonymous"></script>

</body>
</html>